### GroupBY
- 🧠 What is GroupBy?
-- GroupBy means:
+ Group similar values together and perform calculations on them.

In [2]:
import pandas as pd
data = pd.DataFrame({
    "Name":['A', 'B', 'C', 'D', 'E'],
    "Dept": ['IT', 'HR', 'IT', 'IT', 'HR'],
    "Salary": [2000, 5000, 1000, 1500, 2500]
})
data

  Name Dept  Salary
0    A   IT    2000
1    B   HR    5000
2    C   IT    1000
3    D   IT    1500
4    E   HR    2500

Find the Average Salary of All Dept

In [10]:
data.groupby("Dept")["Salary"].mean()

Dept
HR    3750.0
IT    1500.0
Name: Salary, dtype: float64

Find Total Salary of All Department

In [11]:
data.groupby("Dept")["Salary"].sum()

Dept
HR    7500
IT    4500
Name: Salary, dtype: int64

find minimum salary of all Dept

In [12]:
data.groupby("Dept")["Salary"].min()

Dept
HR    2500
IT    1000
Name: Salary, dtype: int64

Count Number of Employee in Each Dept

In [13]:
data.groupby("Dept")["Salary"].count()

Dept
HR    2
IT    3
Name: Salary, dtype: int64

### Multiple Aggregations (Very Important 🔥🔥)

In [14]:
data.groupby("Dept")["Salary"].agg(["mean","sum","max","count"])

        mean   sum   max  count
Dept
HR    3750.0  7500  5000      2
IT    1500.0  4500  2000      3

### Group By Multiple Columns

In [23]:
data.groupby(["Dept","Salary"]).count()

             Name
Dept Salary
HR   2500       1
     5000       1
IT   1000       1
     1500       1
     2000       1

In [11]:
# salary ka avg cal and index add ho jayega
data.groupby("Dept")["Salary"].mean().reset_index()

  Dept  Salary
0   HR  3750.0
1   IT  1500.0

### PRACTICE QUESTION

In [3]:
dataset = pd.DataFrame({
    "city" : ["Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi"],
    "Sales" : [1000, 2000, 1500, 3000, 2000]
})
dataset

     city  Sales
0   Delhi   1000
1  Mumbai   2000
2   Delhi   1500
3  Mumbai   3000
4   Delhi   2000

- 1️⃣ Find total sales per city

In [7]:
dataset.groupby("city")["Sales"].sum()

city
Delhi     4500
Mumbai    5000
Name: Sales, dtype: int64

- 2️⃣ Find average sales per city

In [8]:
dataset.groupby("city")["Sales"].mean()

city
Delhi     1500.0
Mumbai    2500.0
Name: Sales, dtype: float64

- 3️⃣ Find max sales per city

In [9]:
dataset.groupby("city")["Sales"].max()

city
Delhi     2000
Mumbai    3000
Name: Sales, dtype: int64