### Merging Adding and Concatenation

In [2]:
import pandas as pd
import numpy as np

- Merging Two DataFrames

In [15]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,5,7],
    'name': ['peter', 'lambda', 'theta', 'pytho', 'rimi'],
    'dept': ['HR', 'IT', 'IT', "FINANCE", 'HR']
})
# DF2
salaries = pd.DataFrame({
    'employee_id': [1,2,6,8,7],
    'salary': [3200, 2100, 4500, 2300,7800],
    'bonus': [200, 400, 100, 300, 50]
})

In [16]:
employees

   employee_id    name     dept
0            1   peter       HR
1            2  lambda       IT
2            3   theta       IT
3            5   pytho  FINANCE
4            7    rimi       HR

In [17]:
salaries

   employee_id  salary  bonus
0            1    3200    200
1            2    2100    400
2            6    4500    100
3            8    2300    300
4            7    7800     50

- merge both DF
- both can merge by 4 methods 
- 1st - inner, 2nd- outer, 3rd- left, 4th- right

In [19]:
# on = kis column ke base par marge kare 
# how = kaise merge kare option
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id    name dept  salary  bonus
0            1   peter   HR    3200    200
1            2  lambda   IT    2100    400
2            7    rimi   HR    7800     50

In [21]:
# outer = union
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id    name     dept  salary  bonus
0            1   peter       HR  3200.0  200.0
1            2  lambda       IT  2100.0  400.0
2            3   theta       IT     NaN    NaN
3            5   pytho  FINANCE     NaN    NaN
4            6     NaN      NaN  4500.0  100.0
5            7    rimi       HR  7800.0   50.0
6            8     NaN      NaN  2300.0  300.0

In [23]:
# left means employees df ke base par merge karo
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id    name     dept  salary  bonus
0            1   peter       HR  3200.0  200.0
1            2  lambda       IT  2100.0  400.0
2            3   theta       IT     NaN    NaN
3            5   pytho  FINANCE     NaN    NaN
4            7    rimi       HR  7800.0   50.0

In [24]:
# right means salaries df ke base par merge karo
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id    name dept  salary  bonus
0            1   peter   HR    3200    200
1            2  lambda   IT    2100    400
2            6     NaN  NaN    4500    100
3            8     NaN  NaN    2300    300
4            7    rimi   HR    7800     50

### concat

In [28]:
data1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C': ['C0','C1','C2']
})
data2 = pd.DataFrame({
    'A': ['D0','D1','D2'],
    'B': ['E0','E1','E2'],
    'C': ['F0','F1','F2']
})

In [31]:
# By default use axis=0
pd.concat([data1,data2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  D0  E0  F0
1  D1  E1  F1
2  D2  E2  F2

In [32]:
pd.concat([data1,data2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  D0  E0  F0
1  A1  B1  C1  D1  E1  F1
2  A2  B2  C2  D2  E2  F2

Joining

In [40]:
product = pd.DataFrame({
    "Name": ['Laptop', 'Phone', 'Tablet']
}, index=[1,2,3])
prices = pd.DataFrame({
    "Price": [2100, 3100, 1100]
},index=[2,3,4])
product

     Name
1  Laptop
2   Phone
3  Tablet

In [41]:
prices

   Price
2   2100
3   3100
4   1100

In [44]:
# Bydefault left join
# And can also pass how = inner| outer | right
product.join(prices)

     Name   Price
1  Laptop     NaN
2   Phone  2100.0
3  Tablet  3100.0