### Missing Data Learn

In [1]:
import numpy as np
import pandas as pd

In [8]:
data = {
    "Name" : [ "Shashi", "Sonu", "Sumit", None],
    "Age" : [21, 10, None, None],
    "Salary" : [None, None, None, 1000]
}
df = pd.DataFrame(data)
df

     Name   Age  Salary
0  Shashi  21.0     NaN
1    Sonu  10.0     NaN
2   Sumit   NaN     NaN
3     NaN   NaN  1000.0

- Check Missing Values

In [12]:
# isna() provide us when data missing it-True And Data aviable is-False
# df.isnull()
df.isna()

    Name    Age  Salary
0  False  False    True
1  False  False    True
2  False   True    True
3   True   True   False

- Count Each Column How many Data Missing

In [10]:
df.isna().sum()

Name      1
Age       2
Salary    3
dtype: int64

- Check kya ek bhi aisa row hai jisme null value nahi hai

In [19]:
df.isna().any()

Name      True
Age       True
Salary    True
dtype: bool

- Drop missing Data

In [16]:
# Inside Bracket we can pass asix=0 | axis=1
df.dropna()

Empty DataFrame
Columns: [Name, Age, Salary]
Index: []

- Check atleast _kuch value hai jo Non Null hai a

In [21]:
# Kam se kam 2 non null value hone chahiyea
df.dropna(thresh=2)

     Name   Age  Salary
0  Shashi  21.0     NaN
1    Sonu  10.0     NaN

- Fill Missing Data with some Values

In [ ]:
# df.fillna(0)
values = ["Name": "Sahil", "Age": 100, "Salary": 2000]
df.fillna(value=values)

SyntaxError: invalid syntax (3677984603.py, line 2)