About Series in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
lebels = ['a', 'b', 'c']
my_list = [10, 20, 30]
my_dict = {'a': 21, 'b': 31, 'c': 41}
my_arr = np.array([1, 2, 3])

- In Pandas if we don't provide lebels then it automatically
  create lebels 0 1 2
- In Case of Dictonary lebels are these key
- And we can also provide lebels according to us

In [19]:
# Automatically create lebels
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [17]:
# Automatically create lebels
pd.Series(my_arr)

0    1
1    2
2    3
dtype: int64

In [16]:
# Keys of Dict become lebels
pd.Series(my_dict)

a    21
b    31
c    41
dtype: int64

In [23]:
# we Can also provide lebels 
pd.Series(my_list, index=lebels)

a    10
b    20
c    30
dtype: int64

### Data Frame
It's basically a 2-D Structured
(Rows + Column)
- can Create from Dictonary
- Also Can Create from list

- Created by Dict
- Then columns name will be dict 'Keys'

In [ ]:
info = {
    "Name": ["Shashi", "Rahul", "Monu"],
    "Age": [23, 22, 18],
    "Class" : ['XI', 'X', 'VII']
}
df = pd.DataFrame(info)
df

     Name  Age Class
0  Shashi   23    XI
1   Rahul   22     X
2    Monu   18   VII

### Created By Lists
- Data Frame
- in which we get columns name as 0 1 2 ...

In [86]:
product_data = [
    ['Laptop', 16000, 5],
    ['Phone', 12000, 8],
    ['Tablet', 10000, 3]
]
df2 = pd.DataFrame(product_data)
df2

        0      1  2
0  Laptop  16000  5
1   Phone  12000  8
2  Tablet  10000  3

In [ ]:
# Add Columns Name in Product
clm = ['Product', 'Price', 'Quantity']
df2 = pd.DataFrame(product_data, columns=clm)   
df2

  Product  Price  Quantity
0  Laptop  16000         5
1   Phone  12000         8
2  Tablet  10000         3

- Selection of Columns

In [101]:
# Select the column of Product
df2['Product']

0    Laptop
1     Phone
2    Tablet
Name: Product, dtype: str

- Select More than one columns

In [102]:
df2[['Product', 'Price']]

  Product  Price
0  Laptop  16000
1   Phone  12000
2  Tablet  10000

- Add New Columns
Buy_Year = [2021, 2024, 2018]

In [123]:
df2['Buy_Year'] = [2021, 2024, 2018]
df2

  Product  Price  Quantity  Buy_Year
0  Laptop  16000         5      2021
1   Phone  12000         8      2024
2  Tablet  10000         3      2018

- Add A Column Total
- Total = Price * Quantity

In [ ]:
df2["Total"] = df2['Price'] * df2['Quantity']
df2

  Product  Price  Quantity  Buy_Year  Total
0  Laptop  16000         5      2021  80000
1   Phone  12000         8      2024  96000
2  Tablet  10000         3      2018  30000

- Delete a Column

In [131]:
df2.drop('Buy_Year', axis=1)  # Drop column Buy_Year
# df2.drop(0)  # Drop 1st row

  Product  Price  Quantity
0  Laptop  16000         5
1   Phone  12000         8
2  Tablet  10000         3

- Selecting a row

In [134]:
df2.loc[1]

Product     Phone
Price       12000
Quantity        8
Buy_Year     2024
Name: 1, dtype: object

Selection more than 1 row

In [135]:
df2.loc[[0,1]]

  Product  Price  Quantity  Buy_Year
0  Laptop  16000         5      2021
1   Phone  12000         8      2024

- Selection Subsets of Rows And Column

In [142]:
# Select first two rows price and quantity
df2.loc[[0,1], ['Price','Quantity']]

   Price  Quantity
0  16000         5
1  12000         8

- Conditional Selection

In [175]:
df2[df2.Price > 10000]

  Product  Price  Quantity  Buy_Year  Total
0  Laptop  16000         5      2021  80000
1   Phone  12000         8      2024  96000

- find those product whose buy after 2020 and price greater than 10000

In [176]:
df2[(df2['Buy_Year'] > 2020) & (df2['Price'] > 10000)]

  Product  Price  Quantity  Buy_Year  Total
0  Laptop  16000         5      2021  80000
1   Phone  12000         8      2024  96000